services:

  postgres:
    image: postgres:16

    container_name: postgres_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sprintmate_db

    ports:
      - "5432:5432"

    volumes:
      - sprint_mate_postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: sprintmate_app

    restart: always

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:123456@postgres:5432/sprintmate_db
      FRONTEND_URL: http://localhost:5173
      SECRET_KEY: 9f4c2b7a8d3e1f6c0a5b9d8e7f1a2c4b6d9e0f3a7b1c5d8e2f6a9c0b4d7e1f5
      ALGORITHM: HS256
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
      MAIL_USERNAME: sprintmatesystem@gmail.com
      MAIL_PASSWORD: wbks yxhz symr nexk
      EMAIL_USERNAME: sprintmatesystem@gmail.com

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sprintmate_db
      DB_USER: postgres
      DB_PASSWORD: 123456

    ports:
      - "8001:8001"

  pgadmin: 
    image: dpage/pgadmin4 
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports: 
      - "5050:80" 
    depends_on: 
      - postgres

volumes:
  sprint_mate_postgres_data:
